# Generated by Django 4.2.5 on 2023-10-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_R', models.IntegerField()),
                ('voltage_S', models.IntegerField()),
                ('voltage_T', models.IntegerField()),
                ('current_R', models.IntegerField()),
                ('current_S', models.IntegerField()),
                ('current_T', models.IntegerField()),
                ('active_power', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('save_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ActivePower',
        ),
        migrations.DeleteModel(
            name='Current',
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
        migrations.DeleteModel(
            name='Voltage',
        ),
    ]
