# Generated by Django 4.2.5 on 2023-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_ems_delete_activepower_delete_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DCvoltage_R', models.IntegerField()),
                ('DCvoltage_S', models.IntegerField()),
                ('DCvoltage_T', models.IntegerField()),
                ('DCcurrent_R', models.IntegerField()),
                ('DCcurrent_S', models.IntegerField()),
                ('DCcurrent_T', models.IntegerField()),
                ('active_power', models.IntegerField()),
                ('SOC', models.IntegerField()),
                ('SOH', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photovoltaics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_power', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ems',
            name='accumulate_energy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
