# Generated by Django 4.2.5 on 2023-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_battery_save_date_photovoltaics_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ems',
            name='accumulate_energy',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
