# Generated by Django 4.2.6 on 2023-10-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_alter_ems_accumulate_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_power', models.IntegerField()),
                ('save_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
