# Generated by Django 4.2.6 on 2023-11-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_statisticsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsData',
        ),
    ]
